In [ ]:
#Importancion de librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Crear el dataframe
path= "../data/winequality-red.csv"
df=pd.read_csv(path)
display(df.head(10))

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
257,2,114,68,22,0,28.7,0.092,25,0
562,1,87,68,34,77,37.6,0.401,24,0
694,2,90,60,0,0,23.5,0.191,25,0
664,6,115,60,39,0,33.7,0.245,40,1
249,1,111,86,19,0,30.1,0.143,23,0
548,1,164,82,43,67,32.8,0.341,50,0
462,8,74,70,40,49,35.3,0.705,39,0
233,4,122,68,0,0,35.0,0.394,29,0
523,9,130,70,0,0,34.2,0.652,45,1
225,1,87,78,27,32,34.6,0.101,22,0

In [3]:
#Hipotesis: La variable que se nos pide predecir es la Glucosa a partir de una variable explicativa
y = df["Glucose"]
print(y.shape)
display(y.sample(10))

(768,)

533     91
315    112
23     119
103     81
155    152
389    100
750    136
307    137
260    191
320    129
Name: Glucose, dtype: int64

In [5]:
matrix =df.corr()
display(matrix)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [7]:
#Definir variable explicativa
X = df[["Outcome"]]
print(X.shape)
display(X.sample(10))

(768, 1)

     Outcome
536        0
170        1
350        0
399        1
645        0
702        1
264        1
306        1
473        0
372        0

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split       
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [12]:
X_train, X_test, y_train, y_test =train_test_split(X,y,random_state=42, test_size=0.2)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(614, 1)
(154, 1)
(614,)
(154,)

In [18]:
y_train.sample(10)

228    197
485    135
555    124
557    110
223    142
45     180
577    118
535    132
650     91
238    164
Name: Glucose, dtype: int64

In [14]:
model = LinearRegression()
#model.fit(X,y)                   #Posible sobreajuste
model.fit(X_train, y_train)       #Entrenamiento del modelo

LinearRegression()

In [19]:
#Generar predicciones para "evaluar" el modelo
y_pred = model.predict(X_test)
print(y_pred.shape)
y_pred

(154,)

array([110.21446384, 110.21446384, 110.21446384, 110.21446384,
       110.21446384, 110.21446384, 110.21446384, 110.21446384,
       110.21446384, 110.21446384, 140.88732394, 110.21446384,
       140.88732394, 110.21446384, 110.21446384, 140.88732394,
       110.21446384, 110.21446384, 140.88732394, 140.88732394,
       110.21446384, 110.21446384, 110.21446384, 110.21446384,
       110.21446384, 140.88732394, 110.21446384, 110.21446384,
       140.88732394, 110.21446384, 140.88732394, 140.88732394,
       140.88732394, 140.88732394, 110.21446384, 140.88732394,
       140.88732394, 140.88732394, 110.21446384, 140.88732394,
       110.21446384, 110.21446384, 110.21446384, 140.88732394,
       110.21446384, 140.88732394, 140.88732394, 110.21446384,
       110.21446384, 110.21446384, 110.21446384, 140.88732394,
       140.88732394, 140.88732394, 110.21446384, 110.21446384,
       110.21446384, 110.21446384, 110.21446384, 140.88732394,
       140.88732394, 110.21446384, 110.21446384, 140.88732394,
       110.21446384, 110.21446384, 110.21446384, 140.88732394,
       110.21446384, 140.88732394, 110.21446384, 110.21446384,
       110.21446384, 140.88732394, 110.21446384, 110.21446384,
       110.21446384, 110.21446384, 110.21446384, 110.21446384,
       140.88732394, 140.88732394, 110.21446384, 110.21446384,
       110.21446384, 140.88732394, 140.88732394, 140.88732394,
       110.21446384, 110.21446384, 110.21446384, 110.21446384,
       110.21446384, 140.88732394, 110.21446384, 110.21446384,
       110.21446384, 110.21446384, 140.88732394, 110.21446384,
       110.21446384, 110.21446384, 140.88732394, 110.21446384,
       140.88732394, 110.21446384, 110.21446384, 140.88732394,
       140.88732394, 140.88732394, 110.21446384, 110.21446384,
       110.21446384, 140.88732394, 110.21446384, 110.21446384,
       140.88732394, 110.21446384, 110.21446384, 110.21446384,
       110.21446384, 110.21446384, 140.88732394, 110.21446384,
       110.21446384, 110.21446384, 140.88732394, 140.88732394,
       140.88732394, 110.21446384, 140.88732394, 140.88732394,
       110.21446384, 140.88732394, 140.88732394, 110.21446384,
       140.88732394, 140.88732394, 140.88732394, 110.21446384,
       110.21446384, 110.21446384, 110.21446384, 110.21446384,
       110.21446384, 110.21446384, 140.88732394, 110.21446384,
       110.21446384, 140.88732394, 110.21446384, 110.21446384,
       140.88732394, 110.21446384])

In [21]:
#Medir la precision del modelo
r2= r2_score(y_pred, y_test)
mae= mean_absolute_error(y_pred, y_test)
mse=mean_squared_error(y_pred, y_test)

print(f"r2: {r2:.4f}, mae: {mae:.4f}, mse: {mse:.4f}")

r2: -2.4640, mae: 22.0580, mse: 748.2363

In [ ]:
#Definir ecuacion de regresion lineal
print(model.coef_)            #el valor de m
print(model.intercept_)       #el valor de b

[30.6728601]
110.21446384039902